apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tfa.fullname" . }}
  labels:
    {{- include "tfa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tfa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tfa.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "tfa.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $name, $value := .Values.env.variables }}
            - name: {{ $name }}
              value: {{ $value | quote }}
          {{- end }}
          {{- range .Values.env.secrets }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ printf "%s-secrets" (include "tfa.fullname" $) }}
                  key: {{ . }}
          {{- end }}
          volumeMounts:
            - name: rules
              mountPath: /etc/config
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: {{ .Values.service.name }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: rules
          configMap:
            name: {{ include "tfa.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

