apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tfa.fullname" . }}
  labels:
    {{- include "tfa.labels" . | nindent 4 }}
data:
  rules: |
  {{- range $name, $content := .Values.rules }}
    rule.{{ $name }}.rule = {{ .rule }}
    rule.{{ $name }}.action = {{ .action }}
    {{- with .groups }}
    rule.{{ $name }}.groups = {{ . }}
    {{- end }}
  {{- end }}
