{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tfa.serviceAccountName" . }}
  labels:
{{- include "tfa.labels" . | nindent 4 }}
{{- end -}}

