kind: Service
apiVersion: v1
metadata:
  name: {{ include "tfa.fullname" . }}
  labels:
    {{- include "tfa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "tfa.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    name: {{ .Values.service.name }}
status:
  loadBalancer: {}
